name: Build MaterialBinLoader

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26'

    - name: Setup Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MaterialBinLoader
        path: |
          ${{github.workspace}}/build/MaterialBinLoader/**/*.dll
          ${{github.workspace}}/build/Injector/**/*.exe
        if-no-files-found: warn